### ISSUE TITLE
ABBI_SDK | Error | Can't get data because SDK is disabled

### ISSUE THREAD

**Issue by deepanjali11** [abbiio/cordova-plugin-walkme-sdk#1]
Hi @orxelm I am using Version 1.14.5 SDK after ABBI_SDK | Started with SDK (v1.14.5) with app name (version) with app key "value here" showing in logs but getting error "ABBI_SDK | Error | Can't get data because SDK is disabled"
Could you please help this error `ABBI_SDK | Error | Can't get data because SDK is disabled`
Thank You!

**Comment by orxelm** [comment]
Hi @deepanjali11,
Can you please share more info: app key, plugin version, cordova&cordova-ios versions.

**Comment by deepanjali11** [comment]
Started with SDK (v1.14.5) with app Truckstop qa (v5.25.1) with app key 99702a19-b493-4697-8e30-552453823f04
    <plugin name="cordova-plugin-walkme-sdk" spec="1.0.5" />
   <engine name="ios" spec="4.5.5" />
    <engine name="android" spec="7.1.1" />
cordova --version ->8.0.0

**Comment by orxelm** [comment]
Thanks @deepanjali11, 
It seems not related to the cordova plugin.

Can you please contact support@walkme.com to get help faster?
